class Transition:
    def passive_open(self):
        print "Error!"
        return False
    def syn(self):
        print "Error!"
        return False
    def ack(self):
        print "Error!"
        return False
    def rst(self):
        print "Error!"
        return False
    def syn_ack(self):
        print "Error!"
        return False
    def close(self):
        print "Error!"
        return False
    def fin(self):
        print "Error!"
        return False
    def timeout(self):
        print "Error!"
        return False
    def active_open(self):
        print "Error!"
        return False
